### ISSUE TITLE
print warning when cli is out of date

### ISSUE THREAD

**Issue by jaketf** [massdriver-cloud/massdriver-cli#55]
it's easy (even for me) to fall behind the latest release of the CLI. Our cli already needs API token to function so we should have an API endpoint that tracks the latest version of CLI so this can be compared to what is installed. 

- all cli releases registered with API as part of release process
- (option 1) all API requests should set `User-Agent: mass-cli/v.x.x.x` and if this is out of date send back a warning message. This could allow the API to implement logic of if a request from the old version of CLI should be accepted or not.
- (option 2) before each CLI command hit a `latestCLIVersion` endpoint (cache this for future calls with TTL of 1 day)

**Comment by jaketf** [comment]
option to add automated update command

**Comment by WillBeebe** [comment]
Resolved by:

https://github.com/massdriver-cloud/massdriver-cli/pull/69
